name = "goats-wrangler"
type = "rust"
account_id = "17aed4d14e84bd4ae5a6a02e1369ac63"
workers_dev = true
route = ""
zone_id = ""

kv_namespaces = [
    { binding = "GoatsNs", id = "50d119fb12d64caf9212eb7cc5aaa05c", preview_id = "50d119fb12d64caf9212eb7cc5aaa05c" },
    { binding = "FavoritesNs", id = "7915a26ab5d141fab17d50531ae3b4d5", preview_id="7915a26ab5d141fab17d50531ae3b4d5" },
]